### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Slippy2k** [Nun-z/Nun-z.github.io#1]
.

**Comment by Nun-z** [comment]
Hello, thank you for your interest.  I generally do not offer these apps to others in retail mode.  My goal for this guide is to help others to carry out the process for themselves.

See here: https://github.com/Nun-z/XboxRetailModeAppGuide

**Comment by Slippy2k** [comment]
I don't know how to use visual studio despite your instructions, that's why I asked for an access

**Comment by Nun-z** [comment]
Perhaps you could find someone else that has already done this and ask them for access?  Someone you know.  Alternatively, if you know someone that has used Visual Studio before, you could ask them for help.  I can also try to answer any questions you may have about the process.
